services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./configs/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./configs/suricata/rules:/var/lib/suricata/rules
      - ./logs:/var/log/suricata
    command: -i enp0s8 -v

  web_target:
    image: php:8.2-apache
    container_name: web_target
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./logs/apache:/var/log/apache2
    networks:
      - siem-net

  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: siem_syslog_ng
    volumes:
      - ./configs/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ./logs:/var/log/suricata:ro
      - ./logs/apache:/var/log/apache2:ro
    networks:
      - siem-net

networks:
  siem-net:
    driver: bridge