version: "3.8"

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./configs/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./configs/suricata/rules:/var/lib/suricata/rules
      - ./logs:/var/log/suricata
    command: -i enp0s8 -v

  web_target:
    image: php:8.2-apache
    container_name: web_target
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./logs/apache:/var/log/apache2

networks:
  elastic:
    external: true
    name: "elastic"
    
services:
  elasticdb:
    command:
      - "eswrapper"
    container_name: "elasticdb"
    entrypoint:
      - "/bin/tini"
      - "--"
      - "/usr/local/bin/docker-entrypoint.sh"
    environment:
      - "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "container=oci"
      - "ELASTIC_CONTAINER=true"
      - "SHELL=/bin/bash"
    hostname: "1a0ccbecd981"
    image: "docker.elastic.co/elasticsearch/elasticsearch:9.5.5"
    ipc: "private"
    labels:
      architecture: "x86_64"
      build-date: "2026-09-30T07:43:22Z"
      com.redhat.component: "ubi9-minimal-container"
      com.redhat.license_terms: "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"
      cpe: "cpe:/a:redhat:enterprise_linux:9::appstream"
      description: "You know, for search."
      distribution-scope: "public"
      io.buildah.version: "1.44.0"
      io.k8s.description: "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly."
      io.k8s.display-name: "Red Hat Universal Base Image 9 Minimal"
      io.openshift.expose-services: ""
      io.openshift.tags: "minimal rhel9"
      maintainer: "infra@elastic.co"
      name: "Elasticsearch"
      org.label-schema.build-date: "2026-09-30T22:12:03.984586187Z"
      org.label-schema.license: "Elastic-License-2.0"
      org.label-schema.name: "Elasticsearch"
      org.label-schema.schema-version: "1.0"
      org.label-schema.url: "https://www.elastic.co/products/elasticsearch"
      org.label-schema.usage: "https://www.elastic.co/guide/en/elasticsearch/reference/index.html"
      org.label-schema.vcs-ref: "48acba663b09e70b115dd879329141506c377890"
      org.label-schema.vcs-url: "https://github.com/elastic/elasticsearch"
      org.label-schema.vendor: "Elastic"
      org.label-schema.version: "9.5.5"
      org.opencontainers.image.created: "2026-09-30T22:12:03.984586187Z"
      org.opencontainers.image.documentation: "https://www.elastic.co/guide/en/elasticsearch/reference/index.html"
      org.opencontainers.image.licenses: "Elastic-License-2.0"
      org.opencontainers.image.revision: "48acba663b09e70b115dd879329141506c377890"
      org.opencontainers.image.source: "https://github.com/elastic/elasticsearch"
      org.opencontainers.image.title: "Elasticsearch"
      org.opencontainers.image.url: "https://www.elastic.co/products/elasticsearch"
      org.opencontainers.image.vendor: "Elastic"
      org.opencontainers.image.version: "9.5.5"
      release: "1"
      summary: "Elasticsearch"
      url: "https://catalog.redhat.com/en/search?searchType=containers"
      vcs-ref: "f354e3d450169972cb1f8df64acae506d96d4c49"
      vcs-type: "git"
      vendor: "Elastic"
      version: "9.5.5"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "c2:e4:f7:55:78:5a"
    networks:
      - "elastic"
    ports:
      - "9200:9200/tcp"
    stdin_open: true
    tty: true
    user: "1000:0"
    working_dir: "/usr/share/elasticsearch"
  kibanaviewer:
    command:
      - "/usr/local/bin/kibana-docker"
    container_name: "kibanaviewer"
    entrypoint:
      - "/bin/tini"
      - "--"
    environment:
      - "PATH=/usr/share/kibana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "container=oci"
      - "ELASTIC_CONTAINER=true"
    hostname: "d876510c70d7"
    image: "docker.elastic.co/kibana/kibana:9.5.5"
    ipc: "private"

    labels:
      architecture: "x86_64"
      build-date: "2026-09-28T00:37:55Z"
      com.redhat.component: "ubi9-minimal-container"
      com.redhat.license_terms: "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"
      cpe: "cpe:/a:redhat:enterprise_linux:9::appstream"
      description: "Your window into the Elastic Stack."
      distribution-scope: "public"
      io.buildah.version: "1.44.0"
      io.k8s.description: "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly."
      io.k8s.display-name: "Red Hat Universal Base Image 9 Minimal"
      io.openshift.expose-services: ""
      io.openshift.tags: "minimal rhel9"
      maintainer: "infra@elastic.co"
      name: "Kibana"
      org.label-schema.build-date: "2026-09-30T12:22:32.460Z"
      org.label-schema.license: "Elastic License"
      org.label-schema.name: "Kibana"
      org.label-schema.schema-version: "1.0"
      org.label-schema.url: "https://www.elastic.co/products/kibana"
      org.label-schema.usage: "https://www.elastic.co/guide/en/kibana/reference/index.html"
      org.label-schema.vcs-ref: "a2890159e2486503b9e3a0c6f422b153a746651a"
      org.label-schema.vcs-url: "https://github.com/elastic/kibana"
      org.label-schema.vendor: "Elastic"
      org.label-schema.version: "9.5.5"
      org.opencontainers.image.created: "2026-09-30T12:22:32.460Z"
      org.opencontainers.image.documentation: "https://www.elastic.co/guide/en/kibana/reference/index.html"
      org.opencontainers.image.licenses: "Elastic License"
      org.opencontainers.image.revision: "a2890159e2486503b9e3a0c6f422b153a746651a"
      org.opencontainers.image.source: "https://github.com/elastic/kibana"
      org.opencontainers.image.title: "Kibana"
      org.opencontainers.image.url: "https://www.elastic.co/products/kibana"
      org.opencontainers.image.vendor: "Elastic"
      org.opencontainers.image.version: "9.5.5"
      release: "1"
      summary: "Kibana"
      url: "https://catalog.redhat.com/en/search?searchType=containers"
      vcs-ref: "5fed6512327cf4e03d25e424d9f6d5eed9016958"
      vcs-type: "git"
      vendor: "Elastic"
      version: "9.5.5"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "6a:fe:eb:bc:af:07"
    networks:
      - "elastic"
    ports:
      - "5601:5601/tcp"
    user: "1000"
    working_dir: "/usr/share/kibana"

#version: "3.6"
