@version: 4.12
@include "scl.conf"

options {
    stats(freq(1));
    flush_lines(0);
    time_reopen(10);
    use_dns(no);
    use_fqdn(no);
    keep_timestamp(yes);
    owner("root");
    group("root");
    perm(0640);
    create_dirs(yes);
};

# Source 1 : Alertes IDS Suricata
source s_suricata {
    file("/var/log/suricata/eve.json" follow-freq(0.1) flags(no-parse));
};

# Source 2 : Logs d'accès Web Apache
source s_apache {
    file("/var/log/apache2/access.log" follow-freq(0.1) flags(no-parse));
};

# Destinations Elasticsearch
destination d_es_suricata {
    elasticsearch-http(
	persist-name("suricata-eve-dest")
        url("es01:9200/_bulk")
        index("suricata-eve")
        type("")
        user("elastic")
        password("`ELASTIC_PASSWORD`")
        template("$MESSAGE")
    );
};

# Les logs Apache sont du texte. on les parse en champs, puis on envoie du JSON
parser p_apache {
    apache-accesslog-parser(prefix("apache."));
};

destination d_es_apache {
    elasticsearch-http(
	persist-name("apace-access-dest")
        url("es01:9200/_bulk")
        index("apache-access")
        type("")
        user("elastic")
        password("`ELASTIC_PASSWORD`")
        template("$(format-json --scope nv-pairs @timestamp=${ISODATE})")
    );
};

# Pipelines de logs
log {
    source(s_suricata);
    destination(d_es_suricata);
};

log {
    source(s_apache);
    parser(p_apache);
    destination(d_es_apache);
};
