@version: 4.12
@include "scl.conf"

options {
    stats(freq(1));
    flush_lines(0);
    time_reopen(10);
    use_dns(no);
    use_fqdn(no);
    keep_timestamp(yes);
    owner("root");
    group("root");
    perm(0640);
    create_dirs(yes);
};

# Source 1 : Alertes IDS Suricata
source s_suricata {
    file("/var/log/suricata/eve.json" follow-freq(0.1) flags(no-parse));
};

# Source 2 : Logs d'accès Web Apache
source s_apache {
    file("/var/log/apache2/access.log" follow-freq(0.1) flags(no-parse));
};

# Destination unique vers Elasticsearch
destination d_local_test {
    file("/tmp/output_test.log" template("${MESSAGE}\n"));
};

# Pipelines de logs
log {
    source(s_suricata);
    destination(d_local_test);
};

log {
    source(s_apache);
    destination(d_local_test);
};